DROP TABLE IF EXISTS wall_comments CASCADE;

CREATE TABLE wall_comments(
   id SERIAL PRIMARY KEY,
   post_id INT NOT NULL REFERENCES user_wall(id) ON DELETE CASCADE,
   author_id INT REFERENCES users(id) ON DELETE SET NULL,
   comment TEXT NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);